import React, { Component } from 'react';
import { connect } from 'react-redux';
import { meFromToken, meFromTokenSuccess, meFromTokenFailure, resetToken } from '../actions/users';
import App from '../App.js';

const mapDispatchToProps = (dispatch) => {
  return {
  	 loadUserFromToken: () => {
  	 	let token = localStorage.getItem('token');
  	 	if(!token || token === '') {//if there is no token, dont bother
  	 		return;
  	 	}
  	 //fetch user from token (if server deems it's valid token)
      dispatch(meFromToken(token))
        .then((response) => {
          if (!response.error) {
          	//reset token (possibly new token that was regenerated by the server)
          	localStorage.setItem('token', response.payload.config.headers.authorization);
            dispatch(meFromTokenSuccess(response.payload))
          } else {
          	localStorage.removeItem('token');//remove token from storage
            dispatch(meFromTokenFailure(response.payload));
          }
        });
  	 },
     resetMe: () =>{
     	localStorage.removeItem('token'); //remove token from storage
     	dispatch(resetToken());
     }
  }
}


export default connect(null, mapDispatchToProps)(App);