# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1d3f413a65054e4c72f492912fd2c1948a51d18fcb3e835ad757c4327362c66be040de38fdd813fd53a0188ab973ff6a3cf6682decfe3116c6ce74ea83539c3e
  API_KEY: AKIAI6F3HSE4YU3GAAKA
  SECRET_KEY: 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
# 
# test:
#   secret_key_base: 9d1b85bf9b2ef2a6fd14cbc3315faa860919c97400b27aa52ef68ca48829b1d34c5f6b3fe8097206b251faa75dedeca9ebf034205aac419557ab0409d74c7ffb
#     API_KEY: AKIAI6F3HSE4YU3GAAKA
#     SECRET_KEY: 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
# # Do not keep production secrets in the repository,
# # instead read values from the environment.
# production:
#   secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
#   API_KEY: AKIAI6F3HSE4YU3GAAKA
#   SECRET_KEY: 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
